#%RAML 1.0
title: Types Test

types:
  Email:
    type: string
    pattern: ^.+@.+\..+$
  SomeObject:
    type: object
    minProperties: 1
    properties:
      myProp: boolean
  Account:
    description: A basic account in the inheritance test
    properties:
      emails:
        type: Email[]
#     email: Email
      objects:
        type: SomeObject[]
      object:
        type: SomeObject
